### ISSUE TITLE
Ζήτημα δήλωσης πτυχιακής εργασίας. 

### ISSUE THREAD

**Issue by Kavvadias** [courses-ionio/thesis#48]
Καλησπέρα, @epidrome 

βρίσκομαι στον 5ο χρόνο φοίτησης μου στο τμήμα και έχω συμπληρώσει 211 ECTS. Τα μόνα μαθήματα που μου μένουν είναι Επικοινωνία ανθρώπου υπολογιστή και ακομα 3 μαθήματα επιλογής. Θα ήθελα να σας ρωτήσω αν γίνεται και υπάρχει τρόπος να ανοίξω το πεδίο της δήλωσης της πτυχιακής μέχρι 15 Νοεμβρίου. Επικοινωνία ανθρώπου υπολογιστή παρακολουθώ κανονικά το τρέχον εξάμηνο.

**Comment by mkamgit** [comment]
https://github.com/courses-ionio/thesis/wiki

**Comment by epidrome** [comment]
@Kavvadias αυτό που ρωτάς σχετίζεται με κανονισμό του τμήματος και με δήλωση πτυχιακής στην γραμματεία, οπότε θα πρέπει να ρωτήσεις εκεί
